#! /bin/sh
# /etc/init.d/dht_logger
#

echo "$(date "+%Y%m%d %H:%M:%S") dht_logger called with ARG: $1" >> /tmp/dht.log
cd /home/pi/DHT-RaspPi-logger/

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting DHT logger"
    ./DHT_google_docs_logger.py &
    ;;
  stop)
    echo "Stopping DHT logger: attempting to kill `pidof python ./DHT_google_docs_logger.py`"
    kill -9 `pidof python ./DHT_google_docs_logger.py`

    ;;
  *)
    echo "Usage: /etc/init.d/dht_logger {start|stop}"
    exit 1
    ;;
esac

exit 0
