#! /bin/sh
# /etc/init.d/dht_logger
#

echo "$(date "+%Y%m%d %H:%M:%S") dht_logger called with ARG: $1" >> /tmp/dht.log
cd /home/pi/DHT-RaspPi-logger/

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting DHT logger"
    nohup ./DHT_google_docs_logger.py &
    ;;
  stop)
    echo "Stopping DHT logger: attempting to kill `pidof python ./DHT_google_docs_logger.py`"
    kill -9 `pidof python ./DHT_google_docs_logger.py`
    ;;
  status)
    ps -ef | grep python[^*]*DHT
    ;;
  *)
    echo "Usage: /etc/init.d/dht_logger {start|stop|status}"
    echo " OR: service dht_logger {start|stop|status}"
    exit 1
    ;;
esac

exit 0
